# Задача на 4-ом шаге урока

**🛻 Как там твоя Tesla?**

In [1]:
import pandas as pd

In [2]:
path = 'https://raw.githubusercontent.com/a-milenkin/Competitive_Data_Science/main/data/car_info.csv'
car_info = pd.read_csv(path)
car_info.head(3)

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
0,economy,petrol,4.80,2013,42269,P17494612l,Skoda Rapid,engine_overheat,2019,46.650719
1,standart,petrol,4.32,2015,90014,N-1530212S,Renault Sandero,electro_bug,2016,34.377312
2,economy,petrol,4.46,2015,82684,B-1154399t,Smart ForTwo,break_bug,2017,39.157169

In [10]:
df = car_info[car_info['model'] == 'Tesla Model 3']
df

,car_type,fuel_type,car_rating,year_to_start,riders,car_id,model,target_class,year_to_work,target_reg
15,premium,electro,3.90,2017,116872,O-2124190y,Tesla Model 3,gear_stick,2019,50.259303
139,premium,electro,4.68,2014,68359,q-1403429B,Tesla Model 3,engine_check,2019,69.390509
183,premium,electro,3.58,2016,89811,n19871201N,Tesla Model 3,another_bug,2018,100.423402
368,premium,electro,4.64,2016,98304,I13914989Z,Tesla Model 3,engine_ignition,2019,100.618948
429,premium,electro,5.44,2015,75113,g-2283000q,Tesla Model 3,gear_stick,2020,47.949982
543,premium,electro,4.16,2014,56026,P78941617w,Tesla Model 3,engine_fuel,2018,53.111595
773,premium,electro,3.38,2017,131467,h18172982Y,Tesla Model 3,gear_stick,2020,52.616865
854,premium,electro,4.48,2015,91778,r-9019459m,Tesla Model 3,engine_fuel,2021,45.663711
959,premium,electro,4.72,2015,75786,i-1106718P,Tesla Model 3,engine_ignition,2017,119.838023
1271,premium,electro,5.10,2017,120231,I-2073229s,Tesla Model 3,engine_fuel,2017,59.544699
1969,premium,electro,5.12,2015,85734,Q-3414660J,Tesla Model 3,break_bug,2019,48.367762
2041,premium,electro,3.60,2015,86115,N44849090k,Tesla Model 3,electro_bug,2022,55.301032
2089,premium,electro,4.46,2017,125026,s18773736B,Tesla Model 3,gear_stick,2021,59.665744
2173,premium,electro,3.98,2017,132784,T20813001U,Tesla Model 3,engine_fuel,2017,55.180227
2223,premium,electro,4.40,2015,71600,E41968356d,Tesla Model 3,engine_overheat,2020,97.272652
2268,premium,electro,4.82,2015,80038,O-2688441F,Tesla Model 3,engine_fuel,2021,56.281632
2349,premium,electro,4.82,2015,87583,G-1501141U,Tesla Model 3,engine_fuel,2021,79.313938
2485,premium,electro,4.46,2013,39718,L-1156474z,Tesla Model 3,break_bug,2022,69.102557
2616,premium,electro,3.06,2014,66621,p22133368b,Tesla Model 3,electro_bug,2019,63.466226
2894,premium,electro,4.92,2015,89947,u-8176531i,Tesla Model 3,engine_fuel,2021,56.239234
3011,premium,electro,4.92,2014,58631,H-1952766q,Tesla Model 3,gear_stick,2019,50.306346
3018,premium,electro,3.12,2017,135804,T19756755G,Tesla Model 3,another_bug,2018,120.519294
3057,premium,electro,5.56,2013,53647,e-1176726O,Tesla Model 3,engine_fuel,2019,59.222923
3081,premium,electro,5.06,2014,70799,a-2221133L,Tesla Model 3,engine_fuel,2019,57.013603
3093,premium,electro,5.66,2015,87889,v22568580b,Tesla Model 3,engine_check,2021,106.038604
3256,premium,electro,2.76,2017,122592,u12977186v,Tesla Model 3,engine_fuel,2018,62.083205
3267,premium,electro,4.46,2016,105697,l-1177682G,Tesla Model 3,engine_check,2020,77.978439
3362,premium,electro,4.78,2015,93044,h-1921200Q,Tesla Model 3,break_bug,2019,62.858876
3713,premium,electro,4.84,2013,41467,R-1161362E,Tesla Model 3,engine_ignition,2021,118.437034
3900,premium,electro,5.86,2016,88356,D17905231R,Tesla Model 3,engine_overheat,2019,100.816326
3942,premium,electro,4.62,2016,91981,h-5026863d,Tesla Model 3,another_bug,2020,87.479682

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.9/587.9 kB 22.9 MB/s eta 0:00:00

In [18]:
import featuretools as ft
from woodwork.logical_types import Categorical, Double, Datetime, Age, Integer

In [20]:
es = ft.EntitySet(id="car_data")

es = es.add_dataframe(
    dataframe_name="cars",
    dataframe=car_info,
    index="car_id",
    logical_types={
        'car_id': Integer,
        "car_type": Categorical,
        'fuel_type': Categorical,
        'model': Categorical,
        'year_to_start': Age,
        'year_to_work': Age,
        'car_rating': Double,
        'riders': Integer
      }
    )

# Задача на 7-ом шаге урока

**🤩 Выбираем себе дом в LA 🌴**

In [ ]:
# dataset california housing

In [ ]:
!pip install geopandas -q
import geopandas as gpd
from sklearn.datasets import fetch_california_housing

In [ ]:
df = fetch_california_housing(as_frame=True).data
df.head(3)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24

In [ ]:
# создадим GeoDataFrame
gdf = gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df['Longitude'], df['Latitude']),
        crs=4326
    ).to_crs(epsg=3857)
gdf.head(3)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,geometry
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,POINT (-13606581.360 4562487.679)
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,POINT (-13605468.165 4559667.342)
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,POINT (-13607694.555 4558257.461)

In [ ]:
import requests, zipfile, io

county_fname = 'https://github.com/a-milenkin/Competitive_Data_Science/raw/main/data/ca-county-boundaries.zip'
r2 = requests.get(county_fname)
z2 = zipfile.ZipFile(io.BytesIO(r2.content))
z2.extractall("./ca")
ca_counties=gpd.read_file('./ca/CA_Counties').to_crs("EPSG:3857")
gdf = gpd.overlay(gdf, ca_counties[['NAME', 'geometry']], how='intersection')
gdf.head(3)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,NAME,geometry
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,Alameda,POINT (-13606581.360 4562487.679)
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,Alameda,POINT (-13605468.165 4559667.342)
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,Alameda,POINT (-13607694.555 4558257.461)

In [ ]:
# Максимальное расстояние до центра LA

# Минимальное расстояние до центра LA

# Среднее расстояние до центра LA

# Задача на 8-ом шаге урока

**🤯 Не курс, а Санта-Барбара какая-то...**

Для отладки воспользуйтесь примером и датасетом (ca_counties) из демонстрационного ноутбука (или из прошлой задачи):

In [ ]:
ca_counties.head(3)

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,06,091,00277310,06091,Sierra,Sierra County,06,H1,G4020,NaN,NaN,NaN,A,2468694587,23299110,+39.5769252,-120.5219926,"POLYGON ((-13431319.751 4821511.426, -13431312..."
1,06,067,00277298,06067,Sacramento,Sacramento County,06,H1,G4020,472,40900,NaN,A,2499183617,76073827,+38.4500114,-121.3404409,"POLYGON ((-13490651.476 4680831.603, -13490511..."
2,06,083,00277306,06083,Santa Barbara,Santa Barbara County,06,H1,G4020,NaN,42200,NaN,A,7084000598,2729814515,+34.5370572,-120.0399729,"MULTIPOLYGON (((-13423116.772 4042044.149, -13..."

In [ ]:
# Заполните словарь params верными параметрами и их значениями.
# Датасет ca_counties уже записан в переменную ca_counties.

params_1 = {'geo_data': ca_counties,
            '?': ca_counties,
            'columns': ['?', '?'],
            '?': 'feature.properties.NAME',
            '?': '?',
            '?': 'YlGn'}

params_2 = {'?':[34.4208, -119.698],
            '?':5,
            'color':'?',
            '?':'?'}

In [ ]:
import folium

m = folium.Map([37, -122], tiles='OpenStreetMap', zoom_start=6)

# наносим на карту округа с заливкой по площади водного пространства
folium.Choropleth(**params_1).add_to(m)

# наносим на карту город Санта-Барбара
folium.CircleMarker(**params_2).add_to(m)

m

# Задача на 13-ом шаге урока

**Модифицируйте MinimalFCParameters из TSFresh**

In [ ]:
!pip install tsfresh -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.3/95.3 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.2/136.2 kB 5.9 MB/s eta 0:00:00

In [ ]:
# Посмотрим на набор признаков в MinimalFCParameters
from tsfresh.feature_extraction import MinimalFCParameters